name: 'CapRover Actions'
description: 'Create, deploy, and clean up CapRover applications'
inputs:
  caprover_url:
    description: 'CapRover URL'
    required: true
  caprover_password:
    description: 'CapRover password'
    required: true
  app_name:
    description: 'Application name'
    required: true
  image_tag:
    description: 'Image tag for deploy operation'
  image_name:
    description: 'Image name for deploy operation'
  operation:
    description: 'Operation type: create, deploy, cleanup'
    required: true
  docker_registry:
    description: 'docker registry'
    required: false
  useEnv:
    description: 'boolean to use env when updating app'
    required: false
  additionalUpdateSettings:
    description: 'Caprover app settings excluding name and envs as a JSON string'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
